version: '3.2'

services:  
  nginx:
    image: nginx:stable-alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx-https_server.conf:/etc/nginx/nginx-https_server.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
