version: '3.2'

services:  
  nginx:
    image: nginx:1.25.4-bookworm
    build: .
    volumes:
      - /tmp/letsencrypt:/tmp/letsencrypt
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: nginx -g "daemon off;"
